### ISSUE TITLE
webaudio.js and mp3/ogg loading.

### ISSUE THREAD

**Issue by bgc** [jeromeetienne/webaudio.js#15]
i am using webaudio.js without tQuery, and in my current project i have detected that webaudio.js fails to load mp3 file. also in your webpage with the webaudio + threejs tutorial i found a link to another work that uses audio and it didn't play the file.
This happens with Chromium. Later i found out that in Chrome the mp3 files load ok. as it turns out, my Chromium browser only opens ogg files and Chrome opens Ogg and Mp3.
In webaudio.js if a file fails to load, there is a warning in the console, and i think that webaudio.js would benefit if a callback function could be defined if there was an error loading the file (just like the callback function used when the file is loaded).

I have also found a function to detect if the browser supports mp3 or ogg files.
If you think these suggestions are improvements to the library i would gladly help to implement them.

**Comment by jeromeetienne** [comment]
Webaudio.js has no specifc on any file format. This is up to your browser to decode it.

If there is no callback to notify decode error, i will gladlu accept an reasonable implementation of it :)

**Comment by jeromeetienne** [comment]
i got some time and did it, thanks for suggesting this enhancement
