### ISSUE TITLE
AudioContext is not defined

### ISSUE THREAD

**Issue by stevedekorte** [jeromeetienne/webaudio.js#20]
All the demos produce the js error:

  AudioContext is not defined

I'm on OSX 10.8.3 running Chrome Version 26.0.1410.65.

**Comment by jeromeetienne** [comment]
Oh I have ported it to Firefox 2 days ago.  This may explains. Try to do make build? 

All is supposed to works on Chrome. .. I will look when I got time today

**Comment by jeromeetienne** [comment]
Can y you provide an url for a failing demo plus a line number please

**Comment by jeromeetienne** [comment]
it should work now,. tahnks for reporting., reopen if you hit some issues
